### ISSUE TITLE
Tensorflow version

### ISSUE THREAD

**Issue by PeiWoon** [Tonychausan/MyoArmbandPython#1]
Can I know the version of tensorflow of your project ? =D

**Comment by Tonychausan** [comment]
Hi, Sorry for quite late response

The version on the tensorflow is 1.0.0-rc2

**Comment by PeiWoon** [comment]
Thank you. If I have any questions, can I refer to you?

**Comment by Tonychausan** [comment]
Sure :), may I ask what kind of project you are doing?

**Comment by PeiWoon** [comment]
For your project, you are using DFF network, but i am trying to use RNN by modifying the code provided by you.

**Comment by PeiWoon** [comment]
I try to going on on option 0) Try Gesture and face the error as below, do i need to give a value for timestamp and firmware ?


Traceback (most recent call last):
  File "main.py", line 18, in <module>
    main()
  File "main.py", line 15, in main
    menu()
  File "main.py", line 11, in menu
    menu_item_list[action].function()
  File "C:\Users\Asus\Desktop\W Code\MyoArmbandPython-master\src\MenuActions.py", line 129, in live_gesture_recognition
    hub.run(listener, 2000)
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python35\lib\site-packages\myo\_ffi.py", line 571, in run
    six.reraise(*exc_box[0])
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python35\lib\site-packages\six.py", line 692, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python35\lib\site-packages\myo\_ffi.py", line 550, in callback
    result = handler(Event(event))
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python35\lib\site-packages\myo\_device_listener.py", line 43, in on_event
    return method(event)
TypeError: on_paired() missing 2 required positional arguments: 'timestamp' and 'firmware_version

**Comment by Tonychausan** [comment]
That looks like an error from the myo armband API, not sure what is wrong

**Comment by PeiWoon** [comment]
Okay, I try again.
Can i ask that how you collect the dataset in this link
https://github.com/Tonychausan/MyoArmbandProjectData/tree/master/nn_data/emg_network/sessions/2017-06-06-0106

**Comment by Tonychausan** [comment]
The dataset is recorded by using the myo armband and doing the gestures. For more details you can search up my public published master thesis "Machine Learning for Gesture Recognition with Electromyography". Hope that helps a little

**Comment by PeiWoon** [comment]
Thank you. The thesis help a lot.  =D
Between, after I get in the main menu ,there are as shown as below, but how to know the sequences for execute? 
do we need to ensure anything before 0) Try gestures ?

Main Menu
###################################################
0) Try gestures
1) Measurment display
2) Compress Files
3) Delete all compressed files
4) Pre-data gesture test
5) Create Gesture-files
6) Create Gesture-files for not me!
7) Neural Network Menu

Choose an action:

**Comment by talhamaqsood** [comment]
> I try to going on on option 0) Try Gesture and face the error as below, do i need to give a value for timestamp and firmware ?
> 
> Traceback (most recent call last):
> File "main.py", line 18, in 
> main()
> File "main.py", line 15, in main
> menu()
> File "main.py", line 11, in menu
> menu_item_list[action].function()
> File "C:\Users\Asus\Desktop\W Code\MyoArmbandPython-master\src\MenuActions.py", line 129, in live_gesture_recognition
> hub.run(listener, 2000)
> File "C:\Users\Asus\AppData\Local\Programs\Python\Python35\lib\site-packages\myo_ffi.py", line 571, in run
> six.reraise(*exc_box[0])
> File "C:\Users\Asus\AppData\Local\Programs\Python\Python35\lib\site-packages\six.py", line 692, in reraise
> raise value.with_traceback(tb)
> File "C:\Users\Asus\AppData\Local\Programs\Python\Python35\lib\site-packages\myo_ffi.py", line 550, in callback
> result = handler(Event(event))
> File "C:\Users\Asus\AppData\Local\Programs\Python\Python35\lib\site-packages\myo_device_listener.py", line 43, in on_event
> return method(event)
> TypeError: on_paired() missing 2 required positional arguments: 'timestamp' and 'firmware_version

same problem i am having

**Comment by talhamaqsood** [comment]
Try Gesture
Traceback (most recent call last):
  File "C:\Users\STARIZ.PK\PycharmProjects\2ndmilestone\main.py", line 18, in <module>
    main()
  File "C:\Users\STARIZ.PK\PycharmProjects\2ndmilestone\main.py", line 15, in main
    menu()
  File "C:\Users\STARIZ.PK\PycharmProjects\2ndmilestone\main.py", line 11, in menu
    menu_item_list[action].function()
  File "C:\Users\STARIZ.PK\PycharmProjects\2ndmilestone\MenuActions.py", line 124, in live_gesture_recognition
    libmyo.init('../myo-sdk-win-0.9.0/bin')
  File "C:\Users\STARIZ.PK\Anaconda3\lib\site-packages\myo\_ffi.py", line 236, in init
    libmyo = ffi.dlopen(lib_name)
  File "C:\Users\STARIZ.PK\Anaconda3\lib\site-packages\cffi\api.py", line 141, in dlopen
    lib, function_cache = _make_ffi_library(self, name, flags)
  File "C:\Users\STARIZ.PK\Anaconda3\lib\site-packages\cffi\api.py", line 802, in _make_ffi_library
    backendlib = _load_backend_lib(backend, libname, flags)
  File "C:\Users\STARIZ.PK\Anaconda3\lib\site-packages\cffi\api.py", line 797, in _load_backend_lib
    raise OSError(msg)
OSError: cannot load library '../myo-sdk-win-0.9.0/bin': error 0x7e.  Additionally, ctypes.util.find_library() did not manage to locate a library called '../myo-sdk-win-0.9.0/bin'

**Comment by talhamaqsood** [comment]
help me out

**Comment by PeiWoon** [comment]
> OSError: cannot load library '../myo-sdk-win-0.9.0/bin': error 0x7e. Additionally, ctypes.util.find_library() did not manage to locate a library called '../myo-sdk-win-0.9.0/bin'

download myo sdk from this link : https://support.getmyo.com/hc/en-us/articles/360018409792-Myo-Connect-SDK-and-firmware-downloads

then locate at the same place with src folder.(src and myo sdk in the same folder), i think will be okay.

**Comment by PeiWoon** [comment]
> > I try to going on on option 0) Try Gesture and face the error as below, do i need to give a value for timestamp and firmware ?
> > Traceback (most recent call last):
> > File "main.py", line 18, in
> > main()
> > File "main.py", line 15, in main
> > menu()
> > File "main.py", line 11, in menu
> > menu_item_list[action].function()
> > File "C:\Users\Asus\Desktop\W Code\MyoArmbandPython-master\src\MenuActions.py", line 129, in live_gesture_recognition
> > hub.run(listener, 2000)
> > File "C:\Users\Asus\AppData\Local\Programs\Python\Python35\lib\site-packages\myo_ffi.py", line 571, in run
> > six.reraise(*exc_box[0])
> > File "C:\Users\Asus\AppData\Local\Programs\Python\Python35\lib\site-packages\six.py", line 692, in reraise
> > raise value.with_traceback(tb)
> > File "C:\Users\Asus\AppData\Local\Programs\Python\Python35\lib\site-packages\myo_ffi.py", line 550, in callback
> > result = handler(Event(event))
> > File "C:\Users\Asus\AppData\Local\Programs\Python\Python35\lib\site-packages\myo_device_listener.py", line 43, in on_event
> > return method(event)
> > TypeError: on_paired() missing 2 required positional arguments: 'timestamp' and 'firmware_version
> 
> same problem i am having

this is the myo API problem,  hub.run(listener, 2000) should change to hub.run (2000, listener) 

check from these links.
https://myo-python.readthedocs.io/en/latest/myo.html

https://github.com/NiklasRosenstein/myo-python

**Comment by PeiWoon** [comment]
I facing the problem with data length when i run options 0)Try Gestures. Can anyone help me to find out what wrong with that data length? 
I sure that myo armband is working well, and it is functioning with option 1) measurement display, it show the acc, gyroscope , orientation and emg data.


C:\Users\Asus\AppData\Local\Programs\Python\Python35\lib\site-packages\pywt\_multilevel.py:45: UserWarning: Level value of 3 is too high: all coefficients will experience boundary effects.
  "boundary effects.").format(level))
Traceback (most recent call last):
  File "main.py", line 18, in <module>
    main()
  File "main.py", line 15, in main
    menu()
  File "main.py", line 11, in menu
    menu_item_list[action].function()
  File "C:\Users\Asus\Desktop\W Code\MyoArmbandPython-master\src\MenuActions.py", line 159, in live_gesture_recognition
    results = network_session.input_test_emg_network(listener.data_handler)
  File "C:\Users\Asus\Desktop\W Code\MyoArmbandPython-master\src\NeuralNetworkUtility.py", line 726, in input_test_emg_network
    test_inputs = [input_data_handler.get_emg_data_features()]
  File "C:\Users\Asus\Desktop\W Code\MyoArmbandPython-master\src\DataHandlers.py", line 165, in get_emg_data_features
    emg_data_features = numpy.append(self.wavelet_feature_extraxtion(), self.raw_emg_feature_extraxtion())
  File "C:\Users\Asus\Desktop\W Code\MyoArmbandPython-master\src\DataHandlers.py", line 100, in wavelet_feature_extraxtion
    coefficient_subsets = pywt.wavedec(emg_array, 'db1', level=n)
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python35\lib\site-packages\pywt\_multilevel.py", line 102, in wavedec
    a, d = dwt(a, wavelet, mode, axis)
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python35\lib\site-packages\pywt\_dwt.py", line 183, in dwt
    cA, cD = dwt_single(data, wavelet, mode)
  File "pywt\_extensions\_dwt.pyx", line 24, in pywt._extensions._dwt.__pyx_fuse_1dwt_single
  File "pywt\_extensions\_dwt.pyx", line 25, in pywt._extensions._dwt.dwt_single
  File "pywt\_extensions\_dwt.pyx", line 18, in pywt._extensions._dwt.dwt_coeff_len
ValueError: Value of data_len must be greater than zero.

**Comment by talhamaqsood** [comment]
can u give me or help me in making in
use-case diagram
system flow diagram
process flow diagram
class diagram
ofr this project

**Comment by PeiWoon** [comment]
@talhamaqsood
You can refer to this https://www.smartdraw.com/flowchart/flowchart-symbols.htm
And the thesis mentioned above.

**Comment by Tonychausan** [comment]
I dont have access to the myo armband anymore I can't help with you very much. 

I would recommend using Keras instead of vanilla Tensorflow as i did for the network also. Maybe also using Libraries such as pandas to implement cleaner code. As this was done very unclean I wouldn't really recommend to figure out my code too much.
